config/routes.rb
Rails.application.routes.draw do
  # get 'registrations/new'
  # get 'registrations/create'
  # get 'registrations/view'
  # get 'registrations/index'
  # get '/:locale' => 'pages#home'
  scope "(:locale)", locale: /en|fr/ do
    root to: "pages#home"
    resources :registrations
    get "registration_info", to: "registrations#info", as: :info_registration
    get "registration_confirmation/:id", to: "registrations#confirmation", as: :confirmation_registration
    get "information", to: "pages#information", as: :information
    get "pictures", to: "pages#pictures", as: :pictures
    get "partners", to: "pages#partners", as: :partners
    get "schedule_and_results", to: "pages#schedule_and_results", as: :schedule_and_results
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :registrations

  def label
    "#{name} (#{year_min}-#{year_max})"
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  has_and_belongs_to_many :categories
  attr_accessor :year_min, :year_max, :name
  accepts_nested_attributes_for :categories

  validates :category_ids, :presence => { message: :one_category_min }

  validates :firstname, :presence => { message: :no_blank }
  validates :lastname, :presence => { message: :no_blank }
  validates :club_name, :presence => { message: :no_blank }
  validates :country, :presence => { message: :no_blank }
  validates :email,
  :presence => { message: :no_blank },
    :format => {
      :with => /\S+@\S+\.\S+/i,
      :message => :invalid_email
    }
  validates :phone,
  :presence => { message: :no_blank },
    :format => {
      :with => /\A[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}\z/i,
      :message => :invalid_phone
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    {
      locale: I18n.locale,
      host: ENV["DOMAIN"] || "localhost:3000"
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # flash[:notice] = "test flash notice on ruby on rails :)"
  end

  def register
  end

  def information
  end

  def pictures
  end

  def partners
  end

  def schedule_and_results
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def info

  end

  def new
    @registration = Registration.new
    @categories = Category.all
    if params[:registration_info]
      @registration.firstname = params[:registration_info][:firstname] if params[:registration_info][:firstname]
      @registration.lastname = params[:registration_info][:lastname] if params[:registration_info][:lastname]
      @registration.email = params[:registration_info][:email] if params[:registration_info][:email]
      @registration.phone = params[:registration_info][:phone] if params[:registration_info][:phone]
      @registration.club_name = params[:registration_info][:club_name] if params[:registration_info][:club_name]
      @registration.country = params[:registration_info][:country] if params[:registration_info][:country]
      @registration.category_ids = params[:registration_info][:category_ids] if params[:registration_info][:category_ids]
      @firstname_errors =  params[:registration_info][:errors][:firstname]
      @lastname_errors =  params[:registration_info][:errors][:lastname]
      @email_errors =  params[:registration_info][:errors][:email]
      @phone_errors =  params[:registration_info][:errors][:phone]
      @club_name_errors =  params[:registration_info][:errors][:club_name]
      @country_errors =  params[:registration_info][:errors][:country]
      @category_ids_errors =  params[:registration_info][:errors][:category_ids]
    end
  end

  def create
    @registration = Registration.new(registration_params)
    if @registration.save
      redirect_to confirmation_registration_path(@registration)
    else
      redirect_to new_registration_path(
        registration_info: {
          firstname: @registration.firstname,
          lastname: @registration.lastname,
          email: @registration.email,
          phone: @registration.phone,
          club_name: @registration.club_name,
          country: @registration.country,
          category_ids: @registration.category_ids,
          errors: @registration.errors.messages
        }
      )
    end
  end

  def confirmation
    @registration = Registration.find(params[:id])
    @categories = @registration.categories
  end

  def view
  end

  def index
  end

  private

  def registration_params
    params.require(:registration).permit(:firstname, :lastname, :phone, :club_name, :email, :country, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end


  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end


  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Favicon -->
    <%= favicon_link_tag 'favicon-32x32.png' %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-content">
      <%= render "shared/navbar" %>
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<div class="container">
  <%= render "shared/home_presentation" %>
  <%= render "shared/home_partners" %>
</div>

app/views/pages/partners.html.erb
<div class="container">
  <h1><%= t('pages.partners.title') %></h1>
  <%= render "shared/in_progress" %>
</div>

app/views/pages/pictures.html.erb
<div class="container">
  <h1><%= t('pages.pictures.title') %></h1>
  <%= render "shared/in_progress" %>
</div>

app/views/pages/schedule_and_results.html.erb
<div class="container">
  <h1><%= t('pages.schedule_and_results.title') %></h1>
  <%= render "shared/in_progress" %>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
    url('<%= cl_image_path "tjp/tjp_banner" %>')">
    <div class="banner-incrustation">
      <%= cl_image_tag "tjp/logo_whc" %>
      <p class="big-p"><%= t('pages.home.banner_incrustation_title') %></p>
      <p><%= t('pages.home.banner_incrustation_date') %></p>
    </div>
  </div>
  <div class="banner-baseline" >
    <h1><%= t('pages.home.h1') %></h1>
    <p>
      <%= t('pages.home.banner_baseline_start') %>
      <strong><%= t('pages.home.banner_baseline_date') %></strong>
      <%= t('pages.home.banner_baseline_end') %>
    </p>
    <%= link_to t('pages.home.banner_cta'), info_registration_path, class: "btn btn-primary px-4 py-3 rounded-3" %>
  </div>
</div>

app/views/shared/_home_partners.html.erb
<div class="section home-partners">
  <h2><%= t('pages.home.partners_h2') %></h2>
  <div class="partners-list">
    <div class="partner-item">
      <%= cl_image_tag "tjp/credit_mutuel_logo", class: "partner-logo" %>
      <p>Crédit Mutuel</p>
    </div>
    <div class="partner-item">
      <%= cl_image_tag "tjp/zeste_logo", class: "partner-logo" %>
      <p>Zeste Santé</p>
    </div>
    <div class="partner-item">
      <%= cl_image_tag "tjp/brandsfit_logo", class: "partner-logo" %>
      <p>Brandsfit</p>
    </div>
    <div class="partner-item">
      <%= cl_image_tag "tjp/cosy_logo", class: "partner-logo" %>
      <p>Cosy Lunch</p>
    </div>
    <div class="partner-item">
      <%= cl_image_tag "tjp/bc_logo", class: "partner-logo" %>
      <p>BC Nord</p>
    </div>
  </div>
</div>

app/views/shared/_home_presentation.html.erb
<div class="last-edition section">
  <h2><%= t('pages.home.pres_h2') + "..." %></h2>
  <div class="last-edition-flex-container">
    <iframe width="560"
      <%# height="315" %>
      src="https://www.youtube.com/embed/YFKf2Q1P2zI?si=kHaUCt8d_L_DqePM"
      title="YouTube video player"
      frameborder="0"
      allow="accelerometer; clipboard-write; encrypted-media;
      gyroscope; picture-in-picture; web-share"
      referrerpolicy="strict-origin-when-cross-origin"
      allowfullscreen>
    </iframe>
    <ul>
      <li>
        <p>
          <%= "3 " + t('pages.home.pres_days') %>
        </p>
      </li>
      <li>
        <p>
          <%= "6 " + t('pages.home.pres_fields') %>
        </p>
      </li>
      <li>
        <p>
          <%= "64 " + t('pages.home.pres_teams') %>
        </p>
      </li>
      <li>
        <p>
          <%= "4 " + t('pages.home.pres_categories') %>
        </p>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_in_progress.html.erb
<div class="in-progress">
  <i class="fa-solid fa-hammer"></i>
  <p> <%= t('shared.in_progress.description') + ' 😉' %> </p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <img src="https://wattignies-hockey-club.fr/wp-content/uploads/2023/07/logo_WHC.png" alt="WHC Logo">
    <% end %>
      <li class="nav-item dropdown locale-switch">
        <a href="" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          🇫🇷 / 🇬🇧
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Français 🇫🇷", root_path(locale: :fr)  %>
          </li>
          <li>
            <%= link_to "English 🇬🇧", root_path(locale: :en) %>
          </li>
        </ul>
      </li>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to t('pages.home.title'), root_path, class: "nav-link active", 'aria-current': 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to t('registration.title'), info_registration_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item" > %>
            <%# <%= link_to t('pages.information.title'), information_path, class: "nav-link disabled" %>
          <%# </li> %>
          <%# <li class="nav-item" > %>
            <%# <%= link_to t('pages.pictures.title'), pictures_path, class: "nav-link disabled" %>
          <%# </li> %>
          <%# <li class="nav-item" > %>
            <%# <%= link_to t('pages.partners.title'), partners_path, class: "nav-link disabled" %>
          <%# </li> %>
          <%# <li class="nav-item" > %>
            <%# <%= link_to t('pages.schedule_and_results.title'), schedule_and_results_path, class: "nav-link disabled" %>
          <%# </li> %>
        </ul>
      </div>
  </div>
</nav>

app/views/shared/_navbar_wagon.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <%# <% else %>
          <%# <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <%# <% end %>
      </ul>
    </div>
  </div>
</div>